{% set name = "mgrs" %}
{% set version = "1.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ba69009201cb0f3b333fbd098dcf565f5b9d1d04fc5ef9a2c97fd206b7eebac

build:
  number: 1
  skip: True  # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - setuptools
    - wheel

test:
  imports:
    - mgrs

about:
  home: https://github.com/hobu/mgrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'MGRS coordinate conversion for Python'
  dev_url: https://github.com/hobu/mgrs

extra:
  recipe-maintainers:
    - benhuff
    - oblute
    - rluria14
